// Generated by `pnpm db:types` — do not edit manually.
// Run: pnpm db:types
// Requires SUPABASE_PROJECT_ID env var.

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export type Database = Record<string, never>;
